var $jscomp={scope:{}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6-impl","es3");
var emojis="\ud83e\udd70 \ud83d\udcb8 \ud83d\ude4f\ud83c\udffc \ud83c\udfb2 \ud83d\udd25 \ud83c\udf51 \ud83c\udf40 \u2708\ufe0f \ud83d\ude07 \ud83e\udd21 \ud83d\ude08 \u2728 \ud83d\udc7b \ud83d\udc7d \ud83d\udc80 \ud83d\udcb0 \ud83d\udcaf \ud83d\udc51 \ud83d\ude48 \ud83d\udc8e".split(" ");function swap(a,b){var c=emojis[a];emojis[a]=emojis[b];emojis[b]=c}function randomizeEmojis(){for(var a=0;a<emojis.length;a++)swap(a,Math.floor(Math.random()*emojis.length))}randomizeEmojis();
var yxx="         ".split(" "),players=[],count=0,spinning=!1;function createStyle(){var a=document.createElement("style");a.className="styles";document.body.appendChild(a)}createStyle();function updatestyles(){var a=document.querySelector(".styles");a.innerHTML="";for(var b=0;b<count;b++)a.innerHTML+=".style"+b+" {background: "+getColor(b,yxx.length)+"c0;}"}var testinput=document.querySelector("#testinput"),testbtn=document.querySelector("#testbtn");testbtn.addEventListener("click",test1);
testinput.addEventListener("keyup",function(a){13===a.keyCode&&(a.preventDefault(),testbtn.click())});var body=document.querySelector(".body");
function test1(){if(""==testinput.value)return alert("please enter a valid value"),!1;if(20===count)return count;var a=testinput.value;testinput.value="";players.push(a);var b=document.createElement("div");b.classList="bodydiv style"+count;var c=document.createElement("div");c.classList="bodydiv1";c.setAttribute("id","bodydiv"+count);c.addEventListener("click",function(){var a=document.querySelector("."+c.parentNode.classList[1]),b;b=7==c.parentNode.classList[1].length?c.parentNode.classList[1].substring(c.parentNode.classList[1].length-
2):c.parentNode.classList[1].substring(c.parentNode.classList[1].length-1);emojis.push(yxx[b]);for(var d=[],e=0;e<yxx.length;e++)e!=b&&d.push(yxx[e]);10>d.length&&d.push("");yxx=d;a.parentNode.removeChild(a);for(a=0;a<body.children.length;a++)body.children[a].classList="bodydiv style"+a;count--;arc=Math.PI/(yxx.length/2);zr();updatestyles()});var d=document.createElement("h2");d.innerHTML="X";c.appendChild(d);b.appendChild(c);d=document.createElement("div");d.classList=
"bodydiv2";var e=document.createElement("h2");e.innerHTML="$"+a;d.appendChild(e);b.appendChild(d);a=document.createElement("div");a.classList="bodydiv3";d=document.createElement("h2");d.innerHTML=""+emojis[emojis.length-1];a.appendChild(d);b.appendChild(a);body.appendChild(b);10>count?yxx[count]=emojis.pop():yxx.push(emojis.pop());count++;arc=Math.PI/(yxx.length/2);zr();updatestyles()}var testbtn2=document.querySelector("#testbtn2");testbtn2.addEventListener("click",test2);
function test2(){for(i=0;i<count;i++)emojis.push(yxx[i]);count=0;yxx="         ".split(" ");players=[];body.innerHTML="";arc=Math.PI/(yxx.length/2);zr();yz=!1}var zx=1E-6,yz=!1;zq=document.querySelector(".updateJSON");
zq.addEventListener("click",function(a){yz=!0;var b=new XMLHttpRequest;b.onreadystatechange=function(){b.readyState==XMLHttpRequest.DONE&&(zx=JSON.parse(b.responseText).test1)};b.open("GET","https://api.jsonbin.io/b/5ea9ed8107d49135ba47e628/latest",!0);b.send()});random=document.querySelector(".random");random.addEventListener("click",function(a){yz=!1});var startAngle=0,arc=Math.PI/(yxx.length/2),spinTimeout=null,spinArcStart=10,spinTime=0,spinTimeTotal=0,ctx=canvas.getContext("2d");
document.getElementById("spin").addEventListener("click",spin);function byte2Hex(a){return String("0123456789ABCDEF".substr(a>>4&15,1))+"0123456789ABCDEF".substr(a&15,1)}function RGB2Color(a,b,c){return"#"+byte2Hex(a)+byte2Hex(b)+byte2Hex(c)}function getColor(a,b){var c=2*Math.PI/b;red=127*Math.sin(c*a+2)+128;green=127*Math.sin(c*a+0)+128;blue=127*Math.sin(c*a+4)+128;return RGB2Color(red,green,blue)}
function zr(){if(document.getElementById("canvas").getContext){ctx.clearRect(0,0,500,520);ctx.strokeStyle="black";ctx.lineWidth=1;ctx.font="25px Lato, Arial";for(var a=0;a<yxx.length;a++){var b=startAngle+a*arc;ctx.fillStyle=getColor(a,yxx.length)+"ff";ctx.beginPath();ctx.arc(250,250,200,b,b+arc);ctx.stroke();ctx.arc(250,250,125,b+arc,b,!0);ctx.stroke();ctx.fill();ctx.save();ctx.strokeStyle="#0000";ctx.lineWidth=1;ctx.fillStyle="white";ctx.translate(250+160*Math.cos(b+arc/2),
250+160*Math.sin(b+arc/2));ctx.rotate(b+arc/2+Math.PI/2);b=yxx[a];ctx.strokeText(b,-ctx.measureText(b).width/2,0);ctx.fillText(b,-ctx.measureText(b).width/2,0);ctx.restore()}ctx.fillStyle="white";ctx.beginPath();ctx.moveTo(246,45);ctx.lineTo(254,45);ctx.lineTo(254,55);ctx.lineTo(259,55);ctx.lineTo(250,63);ctx.lineTo(241,55);ctx.lineTo(246,55);ctx.lineTo(246,45);ctx.fill()}}function randomNumber(a,b){return Math.random()*(b-a)+a}
function spin(){if(spinning)return!1;spinning=!0;spinAngleStart=yz?21.6433-(21.6433-20.2005)/yxx.length*+zx:21.6433-randomNumber(0,14428)/1E4;spinTime=0;spinTimeTotal=5E3;rotateWheel()}function rotateWheel(){spinTime+=5;if(spinTime>=spinTimeTotal)stopRotateWheel();else{var a=spinAngleStart-easeOut(spinTime,0,spinAngleStart,spinTimeTotal)/1;startAngle+=a*Math.PI/180;zr();spinTimeout=setTimeout("rotateWheel()",1)}}
function stopRotateWheel(){clearTimeout(spinTimeout);var a=Math.floor((360-(180*startAngle/Math.PI+90)%360)/(180*arc/Math.PI));ctx.save();ctx.font="bold 30px Lato, Arial";a=players[a];ctx.fillText(a,250-ctx.measureText(a).width/2,500);ctx.restore();spinning=!1}function easeOut(a,b,c,d){d=(a/=d)*a;return b+c*(d*a+-3*d+3*a)}zr();
